spring.application.name=Career Path Planner

# ----------------------------------------
# Server
# ----------------------------------------
server.port=8081
# ----------------------------------------
# Database - local MySQL (XAMPP / WAMP / standalone)
# ----------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/career_path_planner?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=987654321@Bi

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ----------------------------------------
# Misc
# ----------------------------------------
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#spring.application.name=Career Path Planner

#server.port=${PORT:8080}

#spring.datasource.url=jdbc:mysql://mysql-172f4941-carrerabiraminm3-3275.a.aivencloud.com:27755/defaultdb?ssl-mode=REQUIRED
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none